apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
        - image: docker.io/pashacodefresh/argocd-simulator
          name: simulator
          env:
            - name: HOST
              value: https://adbb4ecc1ac6c48369d68e8a2d90b526-2082982198.us-east-1.elb.amazonaws.com
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: argocd-initial-admin-secret
                  key: password
                  optional: false
            - name: THREADS
              value: "30"
