apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
        - image: docker.io/pashacodefresh/argocd-simulator
          name: simulator
          env:
            - name: HOST
              value: https://argocd-server:443
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: argocd-initial-admin-secret
                  key: password
                  optional: false