apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: system
  source:
    repoURL: https://github.com/alexmt/argo-performance-testing
    path: argo-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
