apiVersion: v1
data:
  url: https://adbb4ecc1ac6c48369d68e8a2d90b526-2082982198.us-east-1.elb.amazonaws.com/
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: b8b5373b3a66d1cf837e
        clientSecret: $dex.github.clientSecret
        orgs:
        - name: argoproj
          teams:
          - argo-cd-admins
kind: ConfigMap
metadata:
  name: argocd-cm
