apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- ./argocd-app.yaml
- ./prometheus-operator-app.yaml
- ./system-proj.yaml

patchesStrategicMerge:
- argocd-server-service-patch.yaml
- argocd-cm.yaml
- argocd-rbac-cm.yaml