apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
spec:
  project: system
  source:
    repoURL: https://github.com/alexmt/argo-performance-testing
    path: prometheus-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus-operator
